language: python
python:
- "3.6"
services: docker
env:
  global:
  # DOCKER_PASS
  - secure: "AFOUsy0kuWRtfATN1bLQttU6hLzG8ahf7jhVpZRoWKXIRAGdicq4rfkAB0bPTuVL17LMgLsn3/HtxIUybLLFy+54ORJwowXfqbm6XeODwMICsJwtiIoYT43Ma9g6Ifm1sqGlN1R6u6p4j8jSZjO3xRhVBz9DKcAmbjcWqnyHNDgrmbmZ33V45oT3AAeO+mESOhcUVDWcKDTuMyiTBTcLP9PfLk667oSQYlwZ2Dv5vhy/Tu3JfOWiIe/HIipK1sSjMekTVpb8KAAcGwm35MUI6iPqNbfhyKVQr6kA4YpKzqpqohgckORhqPhs6d5U1OrKQjB1+lcGXB5UwmDbbzgvGDuCXjFAv7O9rVEGgpHceaWBRG1gfL7A6HxJQPQAGRKrX9hIzdlazKZPFsQUkJONoVTvLgp1s/uA5e+gySa4PrFsC2Uyl5BU46x6B06gAqBKu7Aa69Foq6FGk2RYiF/t/Eeh+eTTxrNeVKPiDXQQEtAlnz9K5ADoBE2EwD7FUnM5BQJJhfkGjE1bslMLso+sIiTsQShq5dLT6Bf2pbLwLT+0TOMjS0uBnx/xMz9E0Q7r8+A1bZXovlBV6nwrQhxxtYZZNHK4nk4PdcmCYf+KvICK1SXFJmQUsxxTYdKlwVGzjpW87z8rBDxSZ7QeI4bfGPeGjQ9qSL4M8toK6O5wI7I="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "E2wa+DSWatvVCO+qwGjDdlwbA8bRKWHNtgExJ7hPYVLqtBuQaX7OOdn6bpbpgf0i4hFbtVANW7HJz8kE07Q20MiUla0gI0vdbuZrW/MZ0YlenC6qvUZ34FpftX9VQi5Kgn57a/DRInDoWvoeFKEA5ERCTsMd0GTgAPpv+BR4xrx4cQp0W9pDrwuZYzrFLCaLwWZHJjYeYRgbvyu1n1ri4jrP45/xbHyRTSxDe3cXwYtBJDvymMwbZkr91gC+lQZUVQM63kCghF8RGatvE7KOkZlNnCEqxeMRr4ueJuk8Iegm8fkiuolpEVS/mqNciE4+bklCFgRfiODUuX+HVRMwMn8jALzbRH5PN2dW6e1aJlWzRPhJcJXeGeYQOOJLLUn6JGwz2caRtdgPYTx7j00gcbuxfN1bGIPhuOjRaM/cVqdA0VBBv+gll5ecylvKRtEhM16yW9LSKEZIRlrXpU4SVVdcLQ7SOKiJN9DPljWyu47QGV5DJRtIwhxhpPRP3rzPxyVBa+9hSVqZURXlEdKEgqssruTpULMgrlDm0sMX2+ER3NlMo9NNb2/rdBsEQ+2q/BgS/Imw3aMp1tJPjVPqhmP+u5Nz0iecNLCB9NZeDU7YLhrwXPafSN/zwAqG19+U1TTBc/+MOLpfzGvGTXfggJ2kBnqsqW47pslMhqoxMkU="
    on_failure: always

before_install: pip install --upgrade requests docker-compose invoke yaml

install: inv dc.build

# script: inv test
script: true

after_success:
- inv ci.tag-build
- inv hub.push
- inv hub.update-readme
